### ISSUE TITLE
Exceptions after update from latest to v1.0.0

### ISSUE THREAD

**Issue by kbakdev** [ritual-net/infernet-container-starter#17]
Traceback (most recent call last):
  File "/app/src/utils/config.py", line 167, in validate_config
    validate(config, path, item.expected_type, item.optional)
  File "/app/src/utils/config.py", line 140, in validate
    validate(config[next_key], path, expected_type, optional)
  File "/app/src/utils/config.py", line 149, in validate
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/main.py", line 292, in <module>
    node.on_startup()
  File "/app/src/main.py", line 64, in on_startup
    config: ConfigDict = load_validated_config(config_path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/utils/config.py", line 184, in load_validated_config
    validate_config(config)
  File "/app/src/utils/config.py", line 169, in validate_config
    raise Exception(f"Missing config param: {item.key_path}")
Exception: Missing config param: chain.registry_address

**Comment by stelios-ritual** [comment]
Yup, your config is stale. Check out the format for the latest config in this repo or [here](https://github.com/ritual-net/infernet-node/blob/main/config.sample.json).

Currently, your problem is that you are missing `registry_address`. See [Registry Addresses](https://docs.ritual.net/infernet/sdk/introduction#deployed-contracts)
